# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


affinity: {}


fleet:
  name: ""

  labels: {}
  #  customer: some-company
  #  game: some-game
  #  region: some-region

  annotations: {}
  #  test: my-test

  scheduling: Packed
  #scheduling: Distributed

  #replicas: 1
  #
  strategy:
    type: RollingUpdate
    #type: Recreate
    maxSurge: 25%
    maxUnavailable: 25%

  networkPolicy:
    enabled: false

gameServer:
  container:
    - name: "default"
      image: ""
      tag: ""
      #registrySecret: ""
      #command: ""
      args: []
      envs: {}
      resources:
        requests:
          memory: "64Mi"
          cpu: "20m"
        limits:
          memory: "64Mi"
          cpu: "20m"
      port:
        containerPort: 7888
        hostPort: 6500
        portPolicy: Dynamic
        protocol: UDP
      ports: 
      - containerPort: 7888
        hostPort: 6500
        portPolicy: Dynamic
        protocol: UDP


  health:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 3

  nodeSelector: {}
    #kubernetes.io/os: windows
    #kubernetes.io/os: linux
    
  tolerations: []

  sdkServer:
    logLevel: Info
    #logLevel: Error
    #logLevel: Debug

    grpcPortEnabled: false
    grpcPort: 9357
    httpPortEnabled: false
    httpPortPort: 9358


dockerRegistry:
  name: "my-secret"
  enabled: false

  secret: ""


autoScaler:
  type: "buffer"
  #type: "webhook"
  
  buffer: 
    bufferSize: 2
    minReplicas: 0
    maxReplicas: 10

  webhook: {}
