---
# https://agones.dev/site/docs/reference/fleet/
# https://agones.dev/site/docs/reference/gameserver/

apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: {{ .Values.fleet.name | default "default-fleet" }}
  {{- if .Values.fleet.labels }}
  labels:
    {{- range $key, $val := .Values.fleet.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.fleet.annotations }}
  annotations:
    {{- range $key, $val := .Values.fleet.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.fleet.replicas }}
  replicas: {{ .Values.fleet.replicas | default "1" }}
  {{- end }}
  scheduling: {{ .Values.fleet.scheduling | default "Packed" }}
  strategy:
    type: {{ .Values.fleet.strategy.type | default "RollingUpdate" }}
    {{- if eq .Values.fleet.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.fleet.strategy.maxSurge }}
      maxUnavailable: {{ .Values.fleet.strategy.maxUnavailable }}
    {{- end }}
  template:
    {{- if .Values.fleet.labels }}
    metadata:
      labels:
        {{- range $key, $val := .Values.fleet.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    {{- end }}
    spec:
      ports:
      {{- range .Values.gameServer.container }}
      - name: {{ .name | quote }}
        containerPort: {{ .port.containerPort }}
        container: {{ .name }}
        portPolicy: {{ .port.portPolicy }}
        protocol: {{ .port.protocol }}
        {{- if eq .port.portPolicy "Static" }}
        hostPort: {{ .port.hostPort }}
        {{- end }}
      {{- end }}
      {{- if .Values.gameServer.health.enabled }}
      health:
        disabled: false
        initialDelaySeconds: {{ .Values.gameServer.health.initialDelaySeconds }}
        periodSeconds: {{ .Values.gameServer.health.periodSeconds }}
        failureThreshold: {{ .Values.gameServer.failureThreshold }}
      {{- end }}
      sdkServer:
        logLevel: {{ .Values.gameServer.sdkServer.logLevel }}
        grpcPort: {{ .Values.gameServer.sdkServer.grpcPort }}
        httpPort: {{ .Values.gameServer.sdkServer.httpPort }}
      template:
        spec:
          containers:
          {{- range .Values.gameServer.container }}
          - name: {{ .name | quote }}
            image: "{{ .image }}:{{ .tag }}"
            #command: [""]
            #args: [""]
            {{- if .env }}
            env:
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            resources:
              requests:
                memory: {{ .resources.requests.memory }}
                cpu: {{ .resources.requests.cpu }}
              limits:
                memory: {{ .resources.limits.memory }}
                cpu: {{ .resources.limits.cpu }}
          {{- end }}
          {{- if .Values.gameServer.registrySecret }}
          imagePullSecrets:
          - name: {{ .Values.gameServer.registrySecret }}
          {{- end }}
          {{- if .Values.gameServer.nodeSelector }}
          nodeSelector:
            {{- range $key, $val := .Values.gameServer.nodeSelector }}
            {{ $key }}: {{ $val | quote }}
            {{- end }}
          {{- end }}
