{{- if .Values.dockerRegistry.enabled }}
---
# kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.name }}
data:
  .dockerconfigjson: {{ .Values.dockerRegistry.secret | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}
