---
# https://agones.dev/site/docs/reference/fleet/
# https://agones.dev/site/docs/reference/gameserver/

apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: {{ .Values.fleet.name | default "default-fleet" }}
  {{- if .Values.fleet.labels }}
  labels:
    {{- range $key, $val := .Values.fleet.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.fleet.annotations }}
  annotations:
    {{- range $key, $val := .Values.fleet.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.fleet.replicas }}
  replicas: {{ .Values.fleet.replicas | default "1" }}
  {{- end }}
  scheduling: {{ .Values.fleet.scheduling | default "Packed" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      {{- if .Values.fleet.labels }}
      metadata:
        labels:
          {{- range $key, $val := .Values.fleet.labels }}
          {{ $key }}: {{ $val | quote }}
          {{- end }}
      {{- end }}
      ports:
      - name: default
        containerPort: 7654
      {{- if .Values.gameServer.health.enabled }}
      health:
        disabled: false
        initialDelaySeconds: {{ .Values.gameServer.health.initialDelaySeconds }}
        periodSeconds: {{ .Values.gameServer.health.periodSeconds }}
        failureThreshold: {{ .Values.gameServer.failureThreshold }}
      {{- end }}
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      template:
        spec:
          containers:
          - name: {{ .Values.gameServer.name | quote }}
            image: "{{ .Values.gameServer.image }}:{{ .Values.gameServer.tag }}"
            #command: [""]
            #args: [""]
            #env:
            #- name: Test
            #  value: Test
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
          {{- if .Values.gameServer.registryCreds }}
          imagePullSecrets:
          - name: regcred
          {{- end }}
          {{- if .Values.gameServer.nodeSelector }}
          nodeSelector:
            {{- range $key, $val := .Values.gameServer.nodeSelector }}
            {{ $key }}: {{ $val | quote }}
            {{- end }}
          {{- end }}
